//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Allen190Prj01.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tMember
    {
        [DisplayName("會員編號")]
        [Required]
        public int MemId { get; set; }
        [DisplayName("會員姓名")]
        public string MemName { get; set; }
        [DisplayName("會員性別")]
        public string MemGender { get; set; }
        [DisplayName("會員電話")]
        public string MemPhone { get; set; }
        [DisplayName("會員Email")]
        public string MemEmail { get; set; }
        [DisplayName("會員生日")]
        public string MemBirthaay { get; set; }
        [DisplayName("會員帳號")]
        [Required]
        public string MemAccount { get; set; }
        [DisplayName("會員密碼")]
        [Required]
        public string MemPassword { get; set; }
    }
}
